services:
  db:
      image: postgres:16
      container_name: postgres-db
      restart: always
      environment:
        POSTGRES_DB: appdb
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
      volumes:
        - postgres_data:/var/lib/postgresql/data
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres -d appdb"]
        interval: 5s
        timeout: 5s
        retries: 5

  backend:
    build: ./backend
    env_file:
      - ./backend/.env    
    depends_on:
      db:
        condition: service_healthy  # Waits for the DB to be fully ready

  frontend:
    build: ./frontend
    depends_on:
      - backend

volumes:
  postgres_data: