/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const COMMUNITY_ID_HEADER: typeof import('./core/api/community').COMMUNITY_ID_HEADER
  const EffectScope: typeof import('vue').EffectScope
  const acceptHMRUpdate: typeof import('pinia').acceptHMRUpdate
  const api: typeof import('./core/api/index').api
  const attachCommunityIdHeader: typeof import('./core/api/community').attachCommunityIdHeader
  const attachCommunityIdParam: typeof import('./core/api/community').attachCommunityIdParam
  const authApi: typeof import('./core/api/authApi').default
  const computed: typeof import('vue').computed
  const createApp: typeof import('vue').createApp
  const createJsonWebSocket: typeof import('./core/api/ws').createJsonWebSocket
  const createPinia: typeof import('pinia').createPinia
  const customRef: typeof import('vue').customRef
  const defineAsyncComponent: typeof import('vue').defineAsyncComponent
  const defineComponent: typeof import('vue').defineComponent
  const defineStore: typeof import('pinia').defineStore
  const del: typeof import('./core/api/helper').del
  const delFullResponse: typeof import('./core/api/helper').delFullResponse
  const effectScope: typeof import('vue').effectScope
  const get: typeof import('./core/api/helper').get
  const getActivePinia: typeof import('pinia').getActivePinia
  const getAnswerStatuses: typeof import('./core/api/constantsApi').getAnswerStatuses
  const getAnswerTypes: typeof import('./core/api/constantsApi').getAnswerTypes
  const getCurrentInstance: typeof import('vue').getCurrentInstance
  const getCurrentScope: typeof import('vue').getCurrentScope
  const getCurrentWatcher: typeof import('vue').getCurrentWatcher
  const getFullResponse: typeof import('./core/api/helper').getFullResponse
  const getSessionStatuses: typeof import('./core/api/constantsApi').getSessionStatuses
  const getStoredCommunityId: typeof import('./core/api/community').getStoredCommunityId
  const getUserStatuses: typeof import('./core/api/constantsApi').getUserStatuses
  const getWithConfig: typeof import('./core/api/helper').getWithConfig
  const h: typeof import('vue').h
  const inject: typeof import('vue').inject
  const isProxy: typeof import('vue').isProxy
  const isReactive: typeof import('vue').isReactive
  const isReadonly: typeof import('vue').isReadonly
  const isRef: typeof import('vue').isRef
  const isShallow: typeof import('vue').isShallow
  const mapActions: typeof import('pinia').mapActions
  const mapGetters: typeof import('pinia').mapGetters
  const mapState: typeof import('pinia').mapState
  const mapStores: typeof import('pinia').mapStores
  const mapWritableState: typeof import('pinia').mapWritableState
  const markRaw: typeof import('vue').markRaw
  const nextTick: typeof import('vue').nextTick
  const onActivated: typeof import('vue').onActivated
  const onBeforeMount: typeof import('vue').onBeforeMount
  const onBeforeRouteLeave: typeof import('vue-router').onBeforeRouteLeave
  const onBeforeRouteUpdate: typeof import('vue-router').onBeforeRouteUpdate
  const onBeforeUnmount: typeof import('vue').onBeforeUnmount
  const onBeforeUpdate: typeof import('vue').onBeforeUpdate
  const onDeactivated: typeof import('vue').onDeactivated
  const onErrorCaptured: typeof import('vue').onErrorCaptured
  const onMounted: typeof import('vue').onMounted
  const onRenderTracked: typeof import('vue').onRenderTracked
  const onRenderTriggered: typeof import('vue').onRenderTriggered
  const onScopeDispose: typeof import('vue').onScopeDispose
  const onServerPrefetch: typeof import('vue').onServerPrefetch
  const onUnmounted: typeof import('vue').onUnmounted
  const onUpdated: typeof import('vue').onUpdated
  const onWatcherCleanup: typeof import('vue').onWatcherCleanup
  const patch: typeof import('./core/api/helper').patch
  const patchFullResponse: typeof import('./core/api/helper').patchFullResponse
  const pinia: typeof import('./core/store/pinia').pinia
  const post: typeof import('./core/api/helper').post
  const postFullResponse: typeof import('./core/api/helper').postFullResponse
  const provide: typeof import('vue').provide
  const publicApi: typeof import('./core/api/publicApi').default
  const publicGet: typeof import('./core/api/helper').publicGet
  const publicPost: typeof import('./core/api/helper').publicPost
  const put: typeof import('./core/api/helper').put
  const putFullResponse: typeof import('./core/api/helper').putFullResponse
  const reactive: typeof import('vue').reactive
  const readonly: typeof import('vue').readonly
  const ref: typeof import('vue').ref
  const resolveComponent: typeof import('vue').resolveComponent
  const resolveWsBaseUrl: typeof import('./core/api/ws').resolveWsBaseUrl
  const setActivePinia: typeof import('pinia').setActivePinia
  const setMapStoreSuffix: typeof import('pinia').setMapStoreSuffix
  const setStoredCommunityId: typeof import('./core/api/community').setStoredCommunityId
  const shallowReactive: typeof import('vue').shallowReactive
  const shallowReadonly: typeof import('vue').shallowReadonly
  const shallowRef: typeof import('vue').shallowRef
  const shouldAttachCommunityId: typeof import('./core/api/community').shouldAttachCommunityId
  const storeToRefs: typeof import('pinia').storeToRefs
  const toRaw: typeof import('vue').toRaw
  const toRef: typeof import('vue').toRef
  const toRefs: typeof import('vue').toRefs
  const toValue: typeof import('vue').toValue
  const triggerRef: typeof import('vue').triggerRef
  const unref: typeof import('vue').unref
  const useAttrs: typeof import('vue').useAttrs
  const useCommunityStore: typeof import('./core/store/community').useCommunityStore
  const useConstantsStore: typeof import('./core/store/constants').useConstantsStore
  const useCssModule: typeof import('vue').useCssModule
  const useCssVars: typeof import('vue').useCssVars
  const useDisableBack: typeof import('./core/composables/usePreventBackBtn').useDisableBack
  const useDisableInspect: typeof import('./core/composables/userPreventInspect').useDisableInspect
  const useId: typeof import('vue').useId
  const useLink: typeof import('vue-router').useLink
  const useModel: typeof import('vue').useModel
  const usePreventRefresh: typeof import('./core/composables/usePreventRefresh').usePreventRefresh
  const useRoute: typeof import('vue-router').useRoute
  const useRouter: typeof import('vue-router').useRouter
  const useSlots: typeof import('vue').useSlots
  const useTemplateRef: typeof import('vue').useTemplateRef
  const useToast: typeof import('./core/composables/useToast').useToast
  const watch: typeof import('vue').watch
  const watchEffect: typeof import('vue').watchEffect
  const watchPostEffect: typeof import('vue').watchPostEffect
  const watchSyncEffect: typeof import('vue').watchSyncEffect
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Component, Slot, Slots, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, ShallowRef, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue'
  import('vue')
  // @ts-ignore
  export type { AnswerStatus, AnswerType, SessionStatus } from './core/api/constantsApi'
  import('./core/api/constantsApi')
}
